name: GitHub Actions-CSDP integration

on:
  workflow_run:
    workflows: [CI - JUnit Calculator Test]
    types: [requested, completed]
  pull_request:
    types: [opened, edited, closed, reopened]

env: 
  NODE_TLS_REJECT_UNAUTHORIZED: 0

jobs:
  octane_integration_job:
    runs-on: octane
    name: OctaneIntegration#${{github.event.action}}#${{github.event.workflow_run.id}}
    steps:
      - name: GitHub Actions ALM Octane Integration
        uses: MicroFocus/alm-octane-github-actions-integration@v23.3.0
        id: gitHubActionsIntegration
        with:
          octaneUrl: 'http://nimbusserver.aos.com:8085/'
          octaneSharedSpace: 1001
          octaneWorkspace: 1002
          octaneClientId: ${{secrets.ALM_OCTANE_CLIENT_ID}}
          octaneClientSecret: ${{secrets.ALM_OCTANE_CLIENT_SECRET}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
          serverBaseUrl: https://github.com/safa50/Calculator
          pipelineNamePattern: '${workflow_name}'
          unitTestResultsGlobPattern: "**/*.xml"
          #gherkinTestResultsGlobPattern: <pattern_for_gherkin_test_result_path>
