name: GitHub Actions-CSDP integration

on:
  workflow_run:
    workflows: [UFT Dev test]
    types: [requested, completed]
  pull_request:
    types: [opened, edited, closed, reopened]

env: 
  NODE_TLS_REJECT_UNAUTHORIZED: 0

jobs:
  octane_integration_job:
    runs-on: csdp
    name: OctaneIntegration#${{github.event.action}}#${{github.event.workflow_run.id}}
    steps:
      - name: GitHub Actions ALM Octane Integration
        uses: MicroFocus/alm-octane-github-actions-integration@v25.1.1
        id: gitHubActionsIntegration
        with:
          octaneUrl: 'https://almoctane-ams.saas.microfocus.com/ui/?p=468005/31002'
          octaneSharedSpace: 468005
          octaneWorkspace: 31002
          octaneClientId: ${{secrets.ALM_OCTANE_CLIENT_ID}}
          octaneClientSecret: ${{secrets.ALM_OCTANE_CLIENT_SECRET}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
          serverBaseUrl: https://github.com/safa50/UFTDev_GitHubActions
          pipelineNamePattern: '${workflow_name}'
          unitTestResultsGlobPattern: "**/*.xml"
          #gherkinTestResultsGlobPattern: <pattern_for_gherkin_test_result_path>
